import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    marginTop: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.09)',
    marginHorizontal: 8,
    paddingHorizontal: 28,
    paddingTop: 30,
    paddingBottom: 58,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    marginBottom: 100,
  },
  absolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.09)',
  },
  titleStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 20,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  titleTextStyle: {
    fontSize: 21,
    color: '#fff',
    fontWeight: '800',
    textAlign: 'center',
  },
  descriptionStyle: {
    fontSize: 18,
    color: '#fff',
    fontWeight: '500',
    marginTop: 30,
    textAlign: 'center',
    opacity: 0.6,
  },
  imageWrapperOuter: {
    height: 112,
    width: 112,
    borderRadius: 112,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 5,
    borderColor: 'rgba(255, 255, 255, 0.16)',
    shadowOffset: {
      width: 0,
      height: 24,
    },
    shadowOpacity: 0.8,
    shadowRadius: 36.0,
    elevation: 24,
    backgroundColor: 'rgba(0,0,0,0.1)',
  },
  imageWrapperInner: {
    height: 88,
    width: 88,
    borderRadius: 88,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    shadowOffset: {
      width: 0,
      height: -24,
    },
    shadowOpacity: 0.8,
    shadowRadius: 36.0,
    elevation: 24,
  },
  imageStyle: {
    height: 46,
    width: 46,
    resizeMode: 'contain',
  },
});
